### PR TITLE
fix: open URL in browser on WSL

### LINKED ISSUE #62: [BUG] Probably does not work with WSL2
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm repo pkg` fails.

### Expected Behavior

`npm repo pkg` should open a browser page with `pkg` repo.

### Steps To Reproduce

```
$ npm repo axios
npm ERR! Cannot read properties of undefined (reading 'stdin')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ai/.npm/_logs/2023-04-09T13_02_08_591Z-debug-0.log
```

### Environment

- npm: 9.5.0
- Node: 18.15.0
- OS: Ubuntu 20.04
- platform: WSL2

### PR DESCRIPTION
**Pull request by mbtools**
Here's a more elegant solution for opening URLs from WSL in your favorite browser. It is based on `sensible-browser` which is included in the default distribution for WSL. This avoids issues with the WSL environment, `cmd.exe`. quoting parameters, etc.

In WSL, set the default browser using the `BROWSER` variable, for example,

```sh
export BROWSER="/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe"
or
export BROWSER="/mnt/c/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"
```

Note: To permanently set the default browser, add the appropriate entry to your shell's RC file, e.g. .bashrc or .zshrc.

To launch a URL from the WSL command line:

```sh
sensible-browser https://google.com
```

To launch a URL using `promise-spawn`:

```js
const promiseSpawn = require('@npmcli/promise-spawn')
promiseSpawn.open('https://google.com')
```

Replaces #118
Closes #62

### Test

```
os: 5.15.153.1-microsoft-standard-WSL2
node: 20.18.0
npm: 10.8.2
```

image

### CODE REVIEW

File: test/open.js [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 const spawk = require('spawk')
 const t = require('tap')
+const os = require('os')
```
Comment (wraithgar) [inline test/open.js:5]:
```suggestion
const os = require('node:os')
```

Comment (wraithgar) [reply test/open.js:5]: We're trying to normalize on this pattern, changing it when we see it as part of any code we're touching, and making sure to use it in new cases.

**Comment by mbtools** [comment]
If BROWSER is not set, it now rejects the promise with a message similar to what you get in WSL cli:

image

I adjusted the tests accordingly

**Review by wraithgar — APPROVED** [review]
